### ISSUE TITLE
Theme netError?

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#37]
The idea with Webconverger's own https://github.com/Webconverger/webconverger-addon/blob/master/src/webconverger-netError.xhtml is that if a page fails to load, it doesn't just sit on the error page.

Perhaps this can be improved:

<img src=http://s.natalian.org/2014-10-17/1413531810_1364x748.png>

    firefox -jsconsole -chrome chrome://webconverger/content/netError.xhtml

**Comment by kaihendry** [comment]
What's the status on this?

We still have https://github.com/Webconverger/webconverger-addon/blob/master/src/webconverger-netError.xhtml#L380

Reading my initial sentiments, I think I just wanted to better explain what we are doing to the user.

Unlike stock Firefox, we must retry since Digital Signs might boot without a connection.

**Comment by mkaply** [comment]
did you see my pull request on this?

**Comment by kaihendry** [comment]
Was it this pull request? https://github.com/Webconverger/webconverger-addon/pull/51

Is this bug fixed?

**Comment by mkaply** [comment]
Yes. This was 51
