### ISSUE TITLE
Options to disable safebrowsing / blocklists

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#43]
These create a lot of noise. We control Addons, so I don't see the value in Mozilla blocking them.
Safebrowsing should be enabled, probably. But I would like to be able to switch it off if I was feeling paranoid! :) Hopefully via the prefs= [API](https://webconverger.org/API/)?

<img src=http://s.natalian.org/2014-12-21/1419164370_1364x748.png>

<img src=http://s.natalian.org/2014-12-21/1419164365_1364x748.png>

**Comment by kaihendry** [comment]
https://twitter.com/gcpascutto/status/546940552873529344

**Comment by mkaply** [comment]
extensions.blocklist.enabled

false

**Comment by mkaply** [comment]
browser.safebrowsing.enabled

false

**Comment by kaihendry** [comment]
I think I need an option other that prefs to set safebrowsing off.
https://www.youtube.com/watch?v=K4xbdM5KHuQ

**Comment by kaihendry** [comment]
I think I want safebrowsing off by default. The NSA stuff on https://en.wikipedia.org/wiki/Google_Safe_Browsing#cite_ref-10 spooked me.

A side effect of doing this is making the packet sniffing less insane. https://www.youtube.com/watch?v=K4xbdM5KHuQ

**Comment by kaihendry** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1057848#c4
