### ISSUE TITLE
Merge proxy support back in ??

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#49]
Hi Mike,

Do you think you could please re-merge in Proxy support into HTTPObserver? I'm not sure why it didn't make it to master, but was present in https://github.com/Webconverger/webc/blob/master/etc/webc/extensions/webconverger/modules/webconvergerModule.jsm

https://github.com/Webconverger/webconverger-addon/commit/0fcdf61912dad20a571dea7413c6233da9cd4220

**Comment by kaihendry** [comment]
On further investigation, I've noticed no Webconverger customer actually using extensions.webconverger.proxyusername. So maybe we should leave it out? =)

**Comment by mkaply** [comment]
I think we should put it in. No harm.

**Comment by mkaply** [comment]
https://github.com/Webconverger/webconverger-addon/pull/52
