### ISSUE TITLE
showprintbutton does not seem to work in Firefox 38

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#54]
I can't easily roll back to Firefox 37 on my Archlinux system, so I am not 100% sure.

Though http://build.webconverger.org/webc-0fa21c1.iso aka https://github.com/Webconverger/webc/commit/0fa21c157325c9cb7ad1a34b6e90495596166dee I can confirm is missing the icon.

**Comment by mkaply** [comment]
https://github.com/Webconverger/webconverger-addon/pull/55
