### ISSUE TITLE
Remove pocket and other unwanted features like hello URLs from FF39

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#58]
<img src=http://s.natalian.org/2015-07-07/pocket.png>

Hey Mike, do you have any time to work on disabling the latest features Mozilla have flung our way?  ;)

**Comment by mkaply** [comment]
Pocket is just a pref.

browser.pocket.enabled

to false

**Comment by kaihendry** [comment]
I can't seem to press return after entering a URL on chrome=webconverger to make the page load when the current state of Webconverger installed.

I wonder what the preference is to disable the reader.

<img src=http://s.natalian.org/2015-07-13/1436763987_1918x1058.png>

**Comment by kaihendry** [comment]
Oops, later realised why URLs were not loading. `pref("extensions.webconverger.whitelist", "mt.dabase.com");` was in my `/usr/lib/firefox/browser/defaults/preferences/webc.js`. Of course there is no warning now. Be good if we could echo on stdout or something so I don't waste time again studying `components/fileBlockService.js` :}

**Comment by kaihendry** [comment]
Fixed in https://github.com/Webconverger/webconverger-addon/commit/a52fd6e79f9bfea0f71209f398b4712d7ba870b5

Opening new bug RE https://support.mozilla.org/en-US/kb/share-firefox-hello-social
