### ISSUE TITLE
Disable Firefox social services

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#59]
This odd sidebar and more feature, I've found to be enabled on Firefox 39:
https://activations.cdn.mozilla.net/
e.g. https://support.mozilla.org/en-US/kb/share-firefox-hello-social

http://s.natalian.org/2015-07-13/disable-me.png
http://s.natalian.org/2015-07-13/services.png

Investigating how to disable this...

**Comment by kaihendry** [comment]
I think this might be called "Firefox social services"... funny.

**Comment by mkaply** [comment]
So there are a couple different things here.

The airplane is one thing. (That's social sharing).

Then there is the social API.

**Comment by kaihendry** [comment]
Thanks for this Mike. I've tested it and deployed it upon https://github.com/Webconverger/webc/commit/775348fbc49762ab9427adba349f51b8513f8463

Sadly these options I came up with didn't work:

    // Disable https://activations.cdn.mozilla.net/
    pref("social.enabled", false);
    pref("social.remote-install.enabled", false);
    pref("social.toast-notifications.enabled", false);

**Comment by mkaply** [comment]
Yeah, they never make it that easy.
