### ISSUE TITLE
Disable Mozilla location services

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#64]
I don't think it's necessary for the fixed type of deployments Webconverger has.

I think we should if off by default with a prefs= ability to re-enable it.

https://www.youtube.com/watch?v=tVPiIruJ7rA

**Comment by kaihendry** [comment]
geo.enabled false should hopefully do the trick. https://www.mozilla.org/en-US/firefox/geolocation/

**Comment by kaihendry** [comment]
Still not working: https://www.youtube.com/watch?v=GXbygG4xOFE

**Comment by hannosch** [comment]
The Mozilla location service isn't actually used for geolocation in the release or beta channels of Firefox. In those channels we use Google's location service. To turn off geolocation setting independent of the actual backend service, setting the "geo.enabled" flag to false is enough.

In the release channels the Mozilla location service is used to help in figure out regional search defaults. You can probably set the "browser.search.geoip.url" pref to an empty string (defaults to: "https://location.services.mozilla.com/v1/country?key=%MOZILLA_API_KEY%"). Setting the "browser.search.geoSpecificDefaults" to false might also work and disable the access to the separate https://search.services.mozilla.com/ service at the same time.

**Comment by bleetsheep** [comment]
`browser.search.geoip.url` is set to an empty string as recommended above, but still seeing a request to `https://location.services.mozilla.com/v1/country?key=xxxxxxxx-a83b-487f-9b5d-xxxxxxxxxxxx` when letting the browser idle. This is in 78.7.0esr from the Debian Bullseye repositories.

One (new?) setting I hadn't touched yet is `browser.search.geoSpecificDefaults` (while `browser.search.geoSpecificDefaults.url` was already cleared to an empty string) which I now set to false, as well as the `geo.enabled` setting above. Perhaps that will do the trick. Note that I'm not actually looking to disable geolocation: when the browser asks to share location with a website and I click yes, then I'd actually like to make use of it.

Bit tricky to make firefox not send requests when I'm not browsing websites, combing through and clearing all the domains and urls in about:config isn't enough anymore...
