### ISSUE TITLE
Disable EME DRM extensions

### ISSUE THREAD

**Issue by kaihendry** [Webconverger/webconverger-addon#65]
https://bugzilla.mozilla.org/show_bug.cgi?id=1044268#c10

I don't think this is a typical requirement for Webconverger installs. Again, be nice to have this off by default, with an option to enable it via prefs= API.

As long as Youtube works flawlessly, I'd rather have it off.

**Comment by kaihendry** [comment]
I'm not 100% sure I can disable this with prefs alone.
https://hacks.mozilla.org/2014/05/reconciling-mozillas-mission-and-w3c-eme/

Any thoughts?

**Comment by mkaply** [comment]
Setting the preference:

media.eme.enabled

to false should stop the downloads.

See:

https://support.mozilla.org/en-US/kb/enable-drm

That's the preference behind "Play DRM Content"

**Comment by kaihendry** [comment]
294	109.482444000	10.0.0.2	aus4.vips.phx1.mozilla.com	TCP	60	58132→https [RST] Seq=366 Win=0 Len=0

These downloads are still happening with `pref("media.eme.enabled", false);`

 http://youtu.be/GXbygG4xOFE

**Comment by mkaply** [comment]
I need to know exactly what files are being downloaded (not just server names).

**Comment by kaihendry** [comment]
I did try to enable DRM just to see if it works and it appears it doesn't... even if wanted to.

https://youtu.be/HxYIoWO4DoA

**Comment by mkaply** [comment]
That's odd. Supposedly all this is working because Netflix works on Linux:

https://www.engadget.com/2017/03/22/netflix-firefox-linux/

I honestly have no idea.
