### ISSUE TITLE
Pocket Button is visible

### ISSUE THREAD

**Issue by fwilhe** [Webconverger/webconverger-addon#69]
Hello,

I've noticed that when I build the xpi from sources (I'm talking about `webconverger.xpi`), and install it in a vanilla firefox 45 Beta (on Linux, downloaded as tarball from mozilla), the pocket button is visible, but without function (the popup is just empty).

I think the button should not be visible in the first place (by adding `#pocket-button,` to `webconverger.css`). Is this a bug?

**Comment by kaihendry** [comment]
We have `pref("browser.pocket.enabled", false);` in our sources, so it should not show. Maybe the way preferences are applied have changed? cc @mkaply

**Comment by mkaply** [comment]
I've started seeing this. We're going to need to add code to remove the button explicitly. I've opened a bugzilla bug.
