### ISSUE TITLE
Whitelisted Download Feature

### ISSUE THREAD

**Issue by fwilhe** [Webconverger/webconverger-addon#70]
For internal needs, we've built a feature to `fileBlockService.js` that allows downloads of certain, whitelisted filetypes. Would this be interesting for the upstream project? If so, I could make a PR out of our patch.

**Comment by kaihendry** [comment]
I don't quite understand the use case for whitelisting file types. Could you give me a case of types some would like to block?

I guess you noticed our domain whitelist. ;)

**Comment by fwilhe** [comment]
We have an enterprise environment where we want to allow only certain file types (pdf, zip, odt, ..), but no shell scripts, executable files etc. This is no real security measurement, I am aware of that.

Apart from that: Webconverger does not allow any downloads, did I get that right? We could contribute this as an optional feature.

**Comment by kaihendry** [comment]
Thank you Florian for the offer. Wouldn't mind looking at the code in a gist or something, but yes since Webconverger doesn't download any non-Web formats (by design), I don't see its utility.

Please review the existing code. Would like to hear more from you. ;)

**Comment by fwilhe** [comment]
All right, so I close this issue.
